### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ChrisPenner** [ChrisPenner/rasa#2]
- [x] Switch Input Events to use adapter system
- [x] Switch Output Display to use adapter system
- [ ] Switch to using [Prisms](https://hackage.haskell.org/package/lens-4.15.1/docs/Control-Lens-Prism.html) for search-related TextLens' to signify whether a result was found.
- [ ]  Generalize notion of 'motions' and 'operators' over Text lenses.
- [ ] Modularize directive system so that editor core is "just another plugin"
- [ ] Support syntax highlighting
- [ ] Generalize cursor interface over multiple cursors (preferable as "just another plugin")
- [ ] Allow Plugins to maintain their own independent state
- [ ] Add 'Save'
- [ ] Add 'Open'
- [ ] Add capacity for user plugins
- [ ] [Add tests for `TextLens`](https://github.com/ChrisPenner/rasa/issues/1)

**Comment by ChrisPenner** [comment]
@Dtatoo Let me know when you have questions, I'm sure there'll be a few!

**Comment by noughtmare** [comment]
> Switch to DYRE??

I recommend against this (at least in the current state of dyre). The [Yi](https://github.com/yi-editor/yi) does this there it has been a source of many problems that newcomers have. I wrote a post about it [here](http://yi-editor.github.io/posts/2017-01-06-dyre/).

My main points are:
  
  * Dyre doesn't handle exceptions smoothly.
  * Dyre doesn't rebuild with cabal or stack (i.e. you just have a single haskell source file as configuration file). This causes a lot of errors related to missing dependencies (like [this one](https://github.com/yi-editor/yi/issues/906)).
  * It is often unclear whether dyre has actually recompiled or not.

I think dyre is an awesome concept, but it still needs more development until its ready to use.

**Comment by ChrisPenner** [comment]
Those are some great points; thanks @noughtmare! 

You're not the first to voice concerns about Dyre; and it definitely wasn't at the top of the priority list anyways. Looks like it's not a great idea, I'll remove it from the list!

I appreciate your feedback on this!

**Comment by clojj** [comment]
Hi,

Maybe for "Per Buffer event/hook system" or a separate TODO entry...

It would be nice to have some kind of '_BufferChanged_' event, indicating some deletion/insertion/.. in text-buffers.
That could be beneficial to any kind of analysis/parsing/lexing extension.

I'd love to help out, if you can point me to the relevant places...

**Comment by ChrisPenner** [comment]
Hey there @clojj! That sounds like a good idea! 

My plan is to limit the API for editing buffers to the operations available using this [range lens]. If you're willing to work on it that would be a great place to start!

Continue the discussion here: https://github.com/ChrisPenner/rasa/issues/20 I've added some bullet points that should help you get started! Post there if you have any questions, or drop into our [Gitter chat](https://gitter.im/rasa-editor/Lobby)

**Comment by clojj** [comment]
Great.
btw. I am pondering what phase is best for colorizing/styling the buffer, after the lexer has tokenized.. ?

I would think that is beforeRender, or ?

**Comment by ChrisPenner** [comment]
`beforeRender` is correct; it's after text-changes have occurred, but before they're rendered to the screen. You can see how the cursors extension renders the cursor here: https://github.com/ChrisPenner/rasa/blob/master/rasa-ext-cursors/src/Rasa/Ext/Cursors/Base.hs#L75 .

This uses elements from `rasa-ext-style` to signal to renderers how to display other ranges. 

We'll likely have to make a few small changes to the way styles are rendered to allow optimizing performance for things like syntax highlighting; having a `bufferChanged` event is going to be useful for that 😁

**Comment by clojj** [comment]
So here is the basic setup of what I am trying to do...
https://github.com/clojj/rasa/blob/master/rasa-example-config/app/Main.hs#L54

I'd like to setup the (Chan String, Chan [Located Token]) in **onInit** of course,
but storing this in **ext** (btw, is **Rasa.Internal.Editor.ext** the editor-global state ? opposed to **bufExt**) is not easy.

As far as it goes, it is working, that is I get all tokens inside the beforeRender handler (lexHaskell)
Lots of todo's for sure :)

**Comment by clojj** [comment]
ok, easier than I thought
https://github.com/clojj/rasa/blob/master/rasa-example-config/app/Main.hs#L84

newtypes galore !

**Comment by ChrisPenner** [comment]
Let's continue the discussion here: https://github.com/ChrisPenner/rasa/issues/24; Looks like you've done a lot of work on this! I'll definitely read it over this weekend!

**Comment by jmatsushita** [comment]
@ChrisPenner Here are some possible new action items to sort through after our gitter pow-wow. 

In order to introduce widgets for autocomplete, file browsing and so on, there seems to be a need to extend the widget functionality to render them elsewhere than at the top/bottom/left/right of a `View`.

 - [ ] Allow Widgets rendering to be:
   - [ ] floating (overlaid maybe above/below/right/left of a specific position in text?)
   - [ ] block (inserted/embedded inside a text block)

Seems that making the Widgets depend on a text position would allow to not leak the rendering abstractions. Does that work?

Also, work in progress on [`rasa-ext-syntax`](https://github.com/iilab/rasa-ext-syntax/) some questions come up about managing file types, language syntax, key maps per language and user configuration. 

 - [ ] Allow Buffers to have types by introducing `data BufTypeChanged bufType = BufTypeChanged`
   - [ ] `BufTypeChanged ReadOnlyBuffer` for read-only buffers in `rasa-ext-files` (`rasa -R example.txt`)
   - [ ] `BufTypeChanged (EditorBuffer languageType)` for specifying syntax choice in `rasa-ext-syntax`. Allowing to make syntax modular by having for instance a markdown syntax extension listen to `BufferTypeChanged (EditorBuffer MarkdownLanguage)`.
   - [ ] `BufTypeChanged FileBrowser` for a file browser in a new 
 - [ ] Dispatch `FileOpened FilePath SomeOtherUsefulStuff` in `rasa-ext-files`
 - [ ] Introduce an extension (and probably some `UserConfig a` event to read user configuration in `dhall` for:
    - [ ] file type to language syntax mappings 
    - [ ] file type to key bindings
    - [ ] key bindings

Should the `BufTypeChanged` type be introduced in `Rasa.Internal.Events` or in an extension?  Should `BufAdded` be extended also to include the `BufType` in addition to the `BufRef`?

**Comment by ChrisPenner** [comment]
Great! I made issues for each of those and put them in a milestone 👍
